# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8644aa2f5319ed4066a9f57b313eda4"
name = "private-app"
handle = "private-app-26"
application_url = "https://offense-licenses-viewers-modify.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "malavipande.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://offense-licenses-viewers-modify.trycloudflare.com/auth/callback",
  "https://offense-licenses-viewers-modify.trycloudflare.com/auth/shopify/callback",
  "https://offense-licenses-viewers-modify.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
